### ISSUE TITLE
Trying to disassemble d64 file

### ISSUE THREAD

**Issue by 621625** [tcarmelveilleux/dcc6502#5]
Hello,

I'm MB. A very nice and polite guy.

Trying to disassemble a d64 file but just getting BRK on every line.

This tool is supposed to be able to disassemble C64 binary files, right?

**Comment by tcarmelveilleux** [comment]
D64 files are disk images that contain a variety of contents, both code and data. DCC6502 will disassemble any code blocks, as long as you know the load address. Extracting code from a D64 file is not easy to do, since each program split the disk in different ways.

See https://vice-emu.sourceforge.io/vice_toc.html#TOC367 for the file format, from which you may extract some code to reverse engineer some more

**Comment by tcarmelveilleux** [comment]
See also https://vice-emu.sourceforge.io/vice_toc.html#TOC367
